#!/bin/bash
mysql -u root -e "DROP DATABASE dumy"
rm /root/asd/myapp/public/img/pornstar/*
rm /root/asd/myapp/public/img/categories/*
rm /root/asd/myapp/public/gif/*
rm /root/asd/data_proper/pornstar_blob
rm /root/asd/data_proper/categories_blob
kill $(pgrep revel)
kill $(pgrep myapp)
