#!/bin/sh
apt update
apt install -y wget tar python3 python3-pip git mysql-server
wget https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
tar -xf go1.16.6.linux-amd64.tar.gz -C /usr/local/ && rm -rf go1.16.6.linux-amd64.tar.gz
PATH=$PATH:/usr/local/go/bin:/$HOME/go/bin
GOROOT=/usr/local/go/
GOPATH=$HOME/go
export PATH GOROOT GOPATH
go get github.com/revel/revel github.com/revel/cmd/revel github.com/jinzhu/gorm github.com/go-sql-driver/mysql
pip3 install requests spintax beautifulsoup4 mysql-connector-python
mysql -u root -e "CREATE DATABASE dumy"
mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost'"
mysql -u root -e "USE mysql; UPDATE user SET plugin='mysql_native_password' WHERE User='root'"
mysql -u root -e "FLUSH PRIVILEGES"
service mysql restart
