#!/bin/sh
sudo apt install -y wget tar

### Download & Build Python ###
wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tar.xz
tar -xf /home/$USER/asd/Python-3.9.6.tar.xz
sh /home/$USER/asd/Python-3.9.6/confgure
make /home/$USER/asd/Python-3.9.6/
sudo make install /home/$USER/asd/Python-3.9.6/

wget https://bootstrap.pypa.io/get-pip.py
sh /home/$USER/asd/Python-3.9.6/python /home/$USER/asd/get-pip.py
