#!/bin/sh
apt update
apt install -y wget tar python3 python3-pip mysql-server
wget https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
tar -xf go1.16.6.linux-amd64.tar.gz -C /usr/local/ && rm -rf go1.16.6.linux-amd64.tar.gz
PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
GOROOT=/usr/local/go/
GOPATH=$HOME/go
export PATH GOROOT GOPATH
go get github.com/revel/revel github.com/revel/cmd/revel github.com/jinzhu/gorm github.com/go-sql-driver/mysql
pip3 install requests spintax beautifulsoup4 mysql-connector-python
#wget https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz
#tar -xf geckodriver-v0.29.1-linux64.tar.gz
#rm geckodriver-v0.29.1-linux64.tar.gz
#mv geckodriver /usr/local/bin
service mysql restart
mysql -u root -e "CREATE DATABASE dumy"
mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost'"
mysql -u root -e "USE mysql; UPDATE user SET plugin='mysql_native_password' WHERE User='root'"
mysql -u root -e "FLUSH PRIVILEGES"

nohup /root/go/bin/revel run /root/asd/myapp > /dev/null 2>&1 & 
sleep 60

#nohup python3 /root/asd/data_proper/insert_gifs > /dev/null 2>&1 & 
#nohup python3 /root/asd/data_proper/download_gifs > /dev/null 2>&1 & 
#nohup python3 /root/asd/data_proper/insert_tags > /dev/null 2>&1 & 

#nohup python3 /root/asd/data_proper/get_pornstar_data > /dev/null 2>&1 & 
#nohup python3 /root/asd/data_proper/insert_pornstars > /dev/null 2>&1 &
#nohup python3 /root/asd/data_proper/download_pornstars > /dev/null 2>&1 &

#nohup python3 /root/asd/data_proper/get_category_data > /dev/null 2>&1 & 
#nohup python3 /root/asd/data_proper/insert_categories > /dev/null 2>&1 & 
#nohup python3 /root/asd/data_proper/download_categories > /dev/null 2>&1 &
